### ISSUE TITLE
Hi, could QTNet support the end2end training? If so, when could the related codes be released?

### ISSUE THREAD

**Issue by Slonna** [AlmoonYsl/QTNet#5]

**Comment by AlmoonYsl** [comment]
Hi, due to the limited resources before, the results in paper are obtained by memory bank training, which is very efficient. Besides, I tried end-to-end training, froze single frame detector (If not frozen, the memory overhead will be very large), and applied temporally consistent data augmentation, whose result is not significantly different from memory bank training.

I am preparing for the rebuttal of CVPR 2024 and the deadline of ECCV 2024, so I don't have free time to clean up the end-to-end training code now. Hope for your understanding.

**Comment by Slonna** [comment]
okay, thanks for your quick reply!
