### ISSUE TITLE
training for waymo open dataset

### ISSUE THREAD

**Issue by DurbinLiu** [AlmoonYsl/QTNet#6]
Hi, congratulations for your great work!
There is one thing I wanna know is that why did you choose Nuscenes but not Waymo Open Dataset for experiments?
And have u trained on WOD before? How does it performs.

**Comment by AlmoonYsl** [comment]
Hi, thanks for your interesting. We think that nuScenes is very suitable for multi-modality and DETR-based detector. 

We want to develop a query-based temporal fusion method for LiDAR, Camera, and multi-modality DETR-based 3D detector. And the performance of DETR-based 3D detector is still inferior to center-based or two-stage 3D detector on WOD during this work. So, we chosen the well-known DETR-based 3D detector TransFusion and nuScenes dataset for experiments. 

Due to limited resources before, we didn't spend a lot of time adjusting QTNet for WOD. But, we conducted some experiments on ConQueR with 20% sequence data, and observed some improvements (about 2 mAP).

**Comment by DurbinLiu** [comment]
> Hi, thanks for your interesting. We think that nuScenes is very suitable for multi-modality and DETR-based detector.
> 
> We want to develop a query-based temporal fusion method for LiDAR, Camera, and multi-modality DETR-based 3D detector. And the performance of DETR-based 3D detector is still inferior to center-based or two-stage 3D detector on WOD during this work. So, we chosen the well-known DETR-based 3D detector TransFusion and nuScenes dataset for experiments.
> 
> Due to limited resources before, we didn't spend a lot of time adjusting QTNet for WOD. But, we conducted some experiments on ConQueR with 20% sequence data, and observed some improvements (about 2 mAP).

I got it, thanks for your fast and detailed reply.
